# Generated by Django 3.2 on 2022-01-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Crop', 'Crop'), ('Vegetable', 'Vegetable'), ('Plantation', 'Plantation'), ('Commercial crop', 'Commercial crop')], max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='dealer',
            fields=[
                ('name', models.TextField(max_length=20)),
                ('dealer_code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='farmer_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('farmer_panjiyan', models.TextField(max_length=20)),
                ('farmer_block', models.TextField(max_length=40)),
                ('farmer_district', models.TextField(max_length=20)),
                ('farmer_village', models.TextField(max_length=20)),
                ('farmer_panchayat', models.TextField(max_length=20)),
                ('farmer_dealer_code', models.ManyToManyField(to='holland.dealer')),
            ],
        ),
    ]
