# Generated by Django 3.2 on 2022-01-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holland', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_detail',
            name='farmer_panjiyan',
            field=models.IntegerField(max_length=20),
        ),
    ]
