# Generated by Django 3.2 on 2022-01-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holland', '0002_alter_farmer_detail_farmer_panjiyan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer_detail',
            name='farmer_dealer_code',
        ),
        migrations.AddField(
            model_name='farmer_detail',
            name='farmer_dealer_code',
            field=models.ForeignKey(default=111999, on_delete=django.db.models.deletion.SET_DEFAULT, to='holland.dealer'),
        ),
        migrations.AlterField(
            model_name='farmer_detail',
            name='farmer_panjiyan',
            field=models.IntegerField(),
        ),
    ]
