# Generated by Django 3.2 on 2022-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holland', '0003_auto_20220123_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_password',
            field=models.SlugField(default='123abc', max_length=10),
        ),
    ]
