# Generated by Django 3.2 on 2022-02-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holland', '0004_dealer_dealer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop-image'),
        ),
    ]
